server:
  port: 10019

spring:
  application:
    name: unimall-service-sendmsg
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    config:
      name: sendmsg
      profile: dev
  config:
    import: configserver:http://127.0.0.1:10010
