server:
  port: 10015

spring:
  application:
    name: unimall-service-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    config:
      name: order
      profile: dev
  config:
    import: configserver:http://127.0.0.1:10010
