server:
  port: 10017

spring:
  application:
    name: unimall-service-comments
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    config:
      name: comments
      profile: dev
  config:
    import: configserver:http://127.0.0.1:10010
